### ISSUE TITLE
Waschmaschine - Gerät fertig funktioniert nicht mehr seit einem der letzten Updates

### ISSUE THREAD

**Issue by martingarber** [Xenon-s/ioBroker.device-reminder#116]
Hallo,

seit einem der letzten Updates funktioniert der Alert nicht mehr, wenn die Waschmaschine fertig hat. Ich habe parallel einen Trockner im System. Dieser funktioniert einwandfrei.
Zum deguggen habe ich das volle Logging aktiviert. Folgenden Fehler kann ich finden, wenn das Gerät fertig hat, die Telegram Nachricht aber nicht gesendet wird:

2021-09-25 13:12:47.733  - [34mdebug[39m: device-reminder.0 (5972) 3: 0 < 1 && 10 >= 10
2021-09-25 13:12:47.733  - [34mdebug[39m: device-reminder.0 (5972) ["Waschmaschine"]: arrStart gelöscht
2021-09-25 13:12:47.733  - [34mdebug[39m: device-reminder.0 (5972) ["Waschmaschine"]: Berechnung beendet
2021-09-25 13:12:47.733  - [34mdebug[39m: device-reminder.0 (5972) ["Waschmaschine"]: Auswertung gestartet
2021-09-25 13:12:47.733  - [34mdebug[39m: device-reminder.0 (5972) ["Waschmaschine"]: WERTE für START3.31; 30; true

2021-09-25 13:12:47.733  - [34mdebug[39m: device-reminder.0 (5972) ["Waschmaschine"]: Vorgang beendet, Gerät fertig
2021-09-25 13:12:47.734  - [31merror[39m: device-reminder.0 (5972) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-09-25 13:12:47.734  - [31merror[39m: device-reminder.0 (5972) unhandled promise rejection: device.dateJSON.push is not a function
2021-09-25 13:12:47.735  - [31merror[39m: device-reminder.0 (5972) TypeError: device.dateJSON.push is not a function
    at deviceReminder.evaluateStatus (/opt/iobroker/node_modules/iobroker.device-reminder/main.js:754:29)
    at deviceReminder.getValues (/opt/iobroker/node_modules/iobroker.device-reminder/main.js:623:20)
2021-09-25 13:12:47.735  - [31merror[39m: device-reminder.0 (5972) device.dateJSON.push is not a function
2021-09-25 13:12:47.739  - [34mdebug[39m: device-reminder.0 (5972) timeout "0": was deleted
2021-09-25 13:12:47.740  - [32minfo[39m: device-reminder.0 (5972) terminating
2021-09-25 13:12:47.740  - [33mwarn[39m: device-reminder.0 (5972) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-09-25 13:12:49.242  - [32minfo[39m: device-reminder.0 (5972) terminating with timeout
2021-09-25 13:12:49.367  - [31merror[39m: host.iobroker instance system.adapter.device-reminder.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

2021-09-25 13:12:49.369  - [32minfo[39m: host.iobroker Restart adapter system.adapter.device-reminder.0 because enabled
2021-09-25 13:13:19.407  - [32minfo[39m: host.iobroker instance system.adapter.device-reminder.0 started with pid 35029
2021-09-25 13:13:19.865  - [34mdebug[39m: device-reminder.0 (35029) Redis Objects: Use Redis connection: 127.0.0.1:9001
2021-09-25 13:13:20.271  - [34mdebug[39m: device-reminder.0 (35029) Objects client ready ... initialize now
2021-09-25 13:13:20.347  - [34mdebug[39m: device-reminder.0 (35029) Objects create System PubSub Client
2021-09-25 13:13:20.348  - [34mdebug[39m: device-reminder.0 (35029) Objects create User PubSub Client
2021-09-25 13:13:20.348  - [34mdebug[39m: device-reminder.0 (35029) Objects client initialize lua scripts
2021-09-25 13:13:20.365  - [34mdebug[39m: device-reminder.0 (35029) Objects connected to redis: 127.0.0.1:9001
2021-09-25 13:13:20.366  - [35msilly[39m: device-reminder.0 (35029) redis psubscribe cfg.o.system.user.*
2021-09-25 13:13:20.369  - [34mdebug[39m: device-reminder.0 (35029) objectDB connected
2021-09-25 13:13:20.376  - [34mdebug[39m: device-reminder.0 (35029) Redis States: Use Redis connection: 127.0.0.1:9000
2021-09-25 13:13:20.443  - [34mdebug[39m: device-reminder.0 (35029) States create System PubSub Client
2021-09-25 13:13:20.444  - [34mdebug[39m: device-reminder.0 (35029) States create User PubSub Client
2021-09-25 13:13:20.507  - [34mdebug[39m: device-reminder.0 (35029) States connected to redis: 127.0.0.1:9000
2021-09-25 13:13:20.507  - [34mdebug[39m: device-reminder.0 (35029) statesDB connected
2021-09-25 13:13:21.034  - [32minfo[39m: device-reminder.0 (35029) starting. Version 1.2.9 in /opt/iobroker/node_modules/iobroker.device-reminder, node: v12.22.4, js-controller: 3.3.15
2021-09-25 13:13:21.056  - [34mdebug[39m: device-reminder.0 (35029) ARR INPUT alexa {}
2021-09-25 13:13:21.056  - [34mdebug[39m: device-reminder.0 (35029) ARR INPUT sayit {}

Ich vermute dass das Problem besteht, seitdem das Standby hinzugefügt wurde.
Wenn ich weitere Tests durchführen soll, bitte einfach Bescheid geben.

lg

Martin

**Comment by Xenon-s** [comment]
bitte den datenpunkt "last operations" löschen und adapter neustarten

**Comment by martingarber** [comment]
Hallo,

vielen Dank. Läuft nun alles wieder einwandfrei!!!

Grüße

Martin
