### ISSUE TITLE
Fehlerhafter eintrag in log

### ISSUE THREAD

**Issue by BenAhrdt** [Xenon-s/ioBroker.device-reminder#365]
Der Log meines ioBrokers sah gerade so aus:
Der Fehler muss während des Laufs aufgetreten sein, da die beiden Geräte Waschmaschine und Trockner beide schon länger liefen.

`
2023-12-11 14:24:43.024 - error: device-reminder.0 (924) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-12-11 14:24:43.031 - error: device-reminder.0 (924) unhandled promise rejection: Converting circular structure to JSON
--> starting at object with constructor 'Timeout'
\| property '_idlePrev' -> object with constructor 'TimersList'
--- property '_idleNext' closes the circle
2023-12-11 14:24:43.031 - error: device-reminder.0 (924) TypeError: Converting circular structure to JSON
--> starting at object with constructor 'Timeout'
\| property '_idlePrev' -> object with constructor 'TimersList'
--- property '_idleNext' closes the circle
at JSON.stringify ()
at sendMsg (/opt/iobroker/node_modules/iobroker.device-reminder/main.js:1144:47)
at deviceReminder.message (/opt/iobroker/node_modules/iobroker.device-reminder/main.js:1151:17)
2023-12-11 14:24:43.031 - error: device-reminder.0 (924) Converting circular structure to JSON
--> starting at object with constructor 'Timeout'
\| property '_idlePrev' -> object with constructor 'TimersList'
--- property '_idleNext' closes the circle
2023-12-11 14:24:43.036 - info: device-reminder.0 (924) terminating
2023-12-11 14:24:43.037 - warn: device-reminder.0 (924) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-12-11 14:24:43.538 - info: device-reminder.0 (924) terminating
2023-12-11 14:24:43.604 - error: host.iobroker instance system.adapter.device-reminder.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
`

**Comment by Xenon-s** [comment]
https://github.com/Xenon-s/ioBroker.device-reminder/issues/344
