### ISSUE TITLE
Adapter Startet nicht

### ISSUE THREAD

**Issue by DerDoubleD** [Xenon-s/ioBroker.device-reminder#73]
**Describe the bug**  
Adapter Startet nicht!

**To Reproduce**  
Drücke START Knopf

**Expected behavior**  

**Screenshots & Logfiles**  
2021-05-15 12:09:44.325 - info: host.iobrokerpi "system.adapter.device-reminder.0" enabled
2021-05-15 12:09:44.432 - info: mqtt.0 (1665) send2Server system.adapter.device-reminder.0.sigKill[system/adapter/device-reminder/0/sigKill]
2021-05-15 12:09:44.465 - info: host.iobrokerpi instance system.adapter.device-reminder.0 started with pid 2482
2021-05-15 12:09:46.093 - info: device-reminder.0 (2482) starting. Version 1.0.6 in /opt/iobroker/node_modules/iobroker.device-reminder, node: v12.22.1, js-controller: 3.2.16
2021-05-15 12:09:46.128 - error: device-reminder.0 (2482) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-05-15 12:09:46.129 - error: device-reminder.0 (2482) unhandled promise rejection: Cannot read property 'stateAction' of undefined
2021-05-15 12:09:46.130 - error: device-reminder.0 (2482) TypeError: Cannot read property 'stateAction' of undefined
at deviceReminder.onReady (/opt/iobroker/node_modules/iobroker.device-reminder/main.js:71:54)
2021-05-15 12:09:46.131 - error: device-reminder.0 (2482) Cannot read property 'stateAction' of undefined
2021-05-15 12:09:46.176 - info: device-reminder.0 (2482) terminating
2021-05-15 12:09:46.178 - warn: device-reminder.0 (2482) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-05-15 12:09:46.864 - error: host.iobrokerpi instance system.adapter.device-reminder.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-05-15 12:09:46.865 - info: host.iobrokerpi Restart adapter system.adapter.device-reminder.0 because enabled
2021-05-15 12:10:16.873 - info: mqtt.0 (1665) send2Server system.adapter.device-reminder.0.sigKill[system/adapter/device-reminder/0/sigKill]
2021-05-15 12:10:16.923 - info: host.iobrokerpi instance system.adapter.device-reminder.0 started with pid 2598
2021-05-15 12:10:18.509 - info: device-reminder.0 (2598) starting. Version 1.0.6 in /opt/iobroker/node_modules/iobroker.device-reminder, node: v12.22.1, js-controller: 3.2.16
2021-05-15 12:10:18.545 - error: device-reminder.0 (2598) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-05-15 12:10:18.546 - error: device-reminder.0 (2598) unhandled promise rejection: Cannot read property 'stateAction' of undefined
2021-05-15 12:10:18.547 - error: device-reminder.0 (2598) TypeError: Cannot read property 'stateAction' of undefined
at deviceReminder.onReady (/opt/iobroker/node_modules/iobroker.device-reminder/main.js:71:54)
2021-05-15 12:10:18.547 - error: device-reminder.0 (2598) Cannot read property 'stateAction' of undefined
2021-05-15 12:10:18.590 - info: device-reminder.0 (2598) terminating
2021-05-15 12:10:18.591 - warn: device-reminder.0 (2598) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-05-15 12:10:19.291 - error: host.iobrokerpi instance system.adapter.device-reminder.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-05-15 12:10:19.293 - info: host.iobrokerpi Restart adapter system.adapter.device-reminder.0 because enabled
2021-05-15 12:10:49.297 - info: mqtt.0 (1665) send2Server system.adapter.device-reminder.0.sigKill[system/adapter/device-reminder/0/sigKill]
2021-05-15 12:10:49.322 - info: host.iobrokerpi instance system.adapter.device-reminder.0 started with pid 2620
2021-05-15 12:10:50.855 - info: device-reminder.0 (2620) starting. Version 1.0.6 in /opt/iobroker/node_modules/iobroker.device-reminder, node: v12.22.1, js-controller: 3.2.16
2021-05-15 12:10:50.893 - error: device-reminder.0 (2620) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-05-15 12:10:50.894 - error: device-reminder.0 (2620) unhandled promise rejection: Cannot read property 'stateAction' of undefined
2021-05-15 12:10:50.895 - error: device-reminder.0 (2620) TypeError: Cannot read property 'stateAction' of undefined
at deviceReminder.onReady (/opt/iobroker/node_modules/iobroker.device-reminder/main.js:71:54)
2021-05-15 12:10:50.896 - error: device-reminder.0 (2620) Cannot read property 'stateAction' of undefined
2021-05-15 12:10:50.948 - info: device-reminder.0 (2620) terminating
2021-05-15 12:10:50.950 - warn: device-reminder.0 (2620) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-05-15 12:10:51.564 - error: host.iobrokerpi instance system.adapter.device-reminder.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2021-05-15 12:10:51.564 - info: host.iobrokerpi Restart adapter system.adapter.device-reminder.0 because enabled
2021-05-15 12:10:51.565 - warn: host.iobrokerpi Do not restart adapter system.adapter.device-reminder.0 because restart loop detected

**Versions:**  
 - Adapter version: 1.0.6
 - JS-Controller version: STABLE up to Date
 - Node version: STABLE up to Date
 - Operating system: Linux

**Comment by Xenon-s** [comment]
Screenshot from log please

**Comment by DerDoubleD** [comment]
![grafik](https://user-images.githubusercontent.com/47006370/118360385-916d3d80-b587-11eb-87ea-6b6241d4caca.png)

**Comment by Xenon-s** [comment]
Please install the latest version of the adapter and follow the instructions in the Admin UI.

**Comment by DerDoubleD** [comment]
![grafik](https://user-images.githubusercontent.com/47006370/118361537-3c7ff600-b58c-11eb-96ea-8cc43f5ade5d.png)

**Comment by Xenon-s** [comment]
Then your entries are incorrect. The adapter has nothing to do with this. Please check the settings.

**Comment by Xenon-s** [comment]
@DerDoubleD Is there anything I can do to help you set it up?

**Comment by DerDoubleD** [comment]
No, Thanks for Help!!!
I reinstalled the Adapter. Now it works fine!
