### ISSUE TITLE
Startet neu während device läuft

### ISSUE THREAD

**Issue by Ghost-Talker** [Xenon-s/ioBroker.device-reminder#75]
Adapter startet immer neu, wenn das Device (Waschmaschine) läuft. 
Dadurch ständig die Telegram (usw.) Nachricht, dass das Device startet.

Problem trat nach neustem Update auf.
Datenpunkte wurden schon neu gesetzt

gekürzte Logfile:

2021-05-22 16:56:21.761 - error: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-05-22 16:56:21.761 - error: device-reminder.0 (15363) unhandled promise rejection: undefined is not a valid state value
2021-05-22 16:56:21.763 - error: device-reminder.0 (15363) Error: undefined is not a valid state value
at /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1588:72
at deviceReminder.setForeignState (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:6013:21)
at /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1585:16
at new Promise ()
at deviceReminder.setForeignStateAsync (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1584:16)
at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.device-reminder/main.js:1333:36)
at listOnTimeout (internal/timers.js:531:17)
at processTimers (internal/timers.js:475:7)
2021-05-22 16:56:21.765 - debug: device-reminder.0 (15363) timeout "0": was deleted
2021-05-22 16:56:21.799 - error: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-05-22 16:56:21.799 - error: device-reminder.0 (15363) unhandled promise rejection: undefined is not a valid state value
2021-05-22 16:56:21.800 - error: device-reminder.0 (15363) Error: undefined is not a valid state value
at /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1588:72
at deviceReminder.setForeignState (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:6013:21)
at /opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1585:16
at new Promise ()
at deviceReminder.setForeignStateAsync (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:1584:16)
at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.device-reminder/main.js:1333:36)
at listOnTimeout (internal/timers.js:531:17)
at processTimers (internal/timers.js:475:7)
2021-05-22 16:56:21.804 - info: device-reminder.0 (15363) terminating
2021-05-22 16:56:21.805 - info: device-reminder.0 (15363) Terminated (NO_ERROR): Without reason
2021-05-22 16:56:22.330 - info: host.ioBroker instance system.adapter.device-reminder.0 terminated with code 0 (NO_ERROR)
2021-05-22 16:56:22.331 - info: host.ioBroker Restart adapter system.adapter.device-reminder.0 because enabled
2021-05-22 16:56:26.426 - info: host.ioBroker "system.adapter.device-reminder.0" disabled

**Versions:**  
 - Adapter version:  1.2.1
 - JS-Controller version: 3.1.4
 - Node version: v12.13.1
 - Operating system: Docker-Container

**Comment by Xenon-s** [comment]
Thx for report, pls screenshots from log

**Comment by Ghost-Talker** [comment]
![image](https://user-images.githubusercontent.com/38839903/119240787-615b0700-bb52-11eb-9074-079494516873.png)

**Comment by Xenon-s** [comment]
The whole thing doesn't look like a bug to me. It seems as if some data point is wrongly selected or it returns a wrong value. Please check the configuration. Is alexa or sayit used? At this point the adapter tries to output a message via voice driverstens, but can't, because apparently the path is incorrect. With Alexa it can only be sent via Speak or Announcement.

**Comment by Ghost-Talker** [comment]
Nach einer Neuinstallation mit identischen Einstellungen scheint es wieder zu funktionieren.

Vielleicht ist ein Fehler bei der Migration zur aktuellen Version entstanden.

**Comment by Ghost-Talker** [comment]
Sorry. 

Ich muss leider noch einmal öffnen.
Fehler taucht wieder auf.
Command speak oder announcment funktioniert eigentlich ohne Probleme (auch mit anderen Adaptern).

Ein neu angelegtes Device (Test) verursacht den selben Fehler.

![image](https://user-images.githubusercontent.com/38839903/120350847-a1af4780-c2ff-11eb-91e7-2cb511c3c6c2.png)
![image](https://user-images.githubusercontent.com/38839903/120350895-ad027300-c2ff-11eb-80e4-909bfcd8e4d5.png)

**Comment by Xenon-s** [comment]
Am Wochenende nehme ich mir die issues hier mal vor 🙂

**Comment by guergen1** [comment]
Ich kann das Verhalten nicht bestätigen (alles auf latest und aktuelle Host-Version)

**Comment by Xenon-s** [comment]
fixed with V 1.2.3

**Comment by Xenon-s** [comment]
fixed with V 1.2.3
